# General Jekyll Config

title: Kevin Phan
logo: /assets/img/logo.png
description: California State University Long Beach College of Engineering - 4th year Graduating spring 2020
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
